version: '1.0'
services:

  mysqlContainer5:
    image: mysql
    ports:
      - "3307:3306"
    environment:
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=mysql123
        - MYSQL_ROOT_PASSWORD=mysql123

  postgresContainer:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"

#  AppContainer:
#    build: ./
#    build:
#      context: "."
#      args:
#        MYSQL_USERNAME: "root"
#        MYSQL_PASSWORD: "mysql123"
#        MYSQL_ROOT_PASSWORD: "mysql123"
#    ports:
#      - "7777:8080"